baseURL = 'https://han-gaeul.github.io/'
languageCode = 'ko-kr'
title = 'hangaeul blog'
theme = 'anatole'

disqusShortname = "XXXXXXXXXXXXXXX"

googleAnalytics = "UA-XXXXXXXXXX-X"

paginate = 7

[author]
    name = "hangaeul"
    email = "hangaeul.dev@gmail.com"